config/routes.rb
Rails.application.routes.draw do

root 'places#index'
resources :places
  
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    Place.create(place_params)
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Nomster</a>
    </div>
    <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <li>
      <%= link_to new_place_path do %>
    <i class="glyphicon glyphicon-plus-sign"></i>
    New Place
  <% end %>

    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="#">Link</a></li>
  </ul>
</div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<% @places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= place.name %></h1>
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />
  </div>
<% end %>

app/views/places/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
     <%= f.submit 'Create' %>
     <br/>
      <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>